lwa4p_red:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  arm_1_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_1_joint
    pid: {p: 2000.0, i: 0.0, d: 0.0}
  arm_2_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_2_joint
    pid: {p: 2000.0, i: 0.0, d: 0.0}
  arm_3_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_3_joint
    pid: {p: 2000.0, i: 0.0, d: 0.0}
  arm_4_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_4_joint
    pid: {p: 2020.0, i: 0.0, d: 0.0}
  arm_5_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_5_joint
    pid: {p: 2030.0, i: 0.0, d: 0.0}
  arm_6_joint_pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_6_joint
    pid: {p: 2050.0, i: 0.0, d: 0.0}


  # Velocity Controllers ---------------------------------------
  arm_1_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_1_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
  arm_2_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_2_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
  arm_3_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_3_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
  arm_4_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_4_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
  arm_5_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_5_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
  arm_6_joint_vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_6_joint
    pid: {p: 2.0, i: 0.0, d: 0.0}
